version: '3.8'

services:
  fiap-pay:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - app-network

  database:
    build: ./docker
    environment:
      POSTGRES_DB: fiappay
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS=--auth-host: scram-sha-256
    ports:
      - "5433:5432"
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
        - app-network

networks:
  app-network:
    driver: bridge