spring:
  application:
    name: fiap-pay

  docker:
    compose:
      file: ./docker-compose.yaml

  datasource:
    url: jdbc:postgresql://localhost:5433/fiappay?createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      schema: ${spring.application.name}
  liquibase:
    change-log: db/changelog/changelog-master.xml

springdoc:
  swagger-ui:
    tags-sorter: alpha

jwt:
  secret: 79063e8037fff16d297a1fe65136f1251126cddb2cc9870ecf8d653835538e85